Repository CloudInn/ng-crud-ui, pull requests merged in 2019-02, with the labels that each got.

#24 Fix(#8): Fixed ForeignKey Field value evaluation
  docs/assets/docs/foreignKeys.md
  json-mock/db.json
  projects/crud/src/lib/components/auto-complete-field/auto-complete-field.component.ts
  projects/crud/src/lib/components/foreign-key-field/foreign-key-field.component.html
  projects/crud/src/lib/components/foreign-key-field/foreign-key-field.component.ts
  projects/crud/src/lib/components/form-field/form-field.component.html
  projects/crud/src/lib/components/form-field/form-field.component.ts
  projects/crud/src/lib/components/listing/listing.component.html
  projects/crud/src/lib/components/listing/listing.component.ts
  projects/crud/src/lib/components/model-form/model-form.component.html
  projects/crud/src/lib/components/model-form/model-form.component.ts
  projects/crud/src/lib/components/select-field/select-field.component.ts
  projects/crud/src/lib/components/text-area-field/text-area-field.component.ts
  projects/crud/src/lib/containers/listing-dialog/listing-dialog.component.ts
  projects/crud/src/lib/crud.module.ts
  projects/crud/src/lib/models/metadata.ts
  projects/crud/src/lib/models/views.ts
  projects/crud/src/lib/services/form.service.ts
  projects/crud/src/public_api.ts
  projects/docs/src/assets/docs/foreignKeys.md
  projects/example-app/src/app/app.component.ts
  projects/example-app/src/app/forms/room.edit.form.ts
  projects/example-app/src/app/forms/store.search.form.ts
  projects/example-app/src/app/forms/terminal.search.form.ts
  projects/example-app/src/app/metadata/department.metadata.ts
  projects/example-app/src/app/metadata/room.metadata.ts
  projects/example-app/src/app/metadata/store.metadata.ts
  projects/example-app/src/app/metadata/terminal.metadata.ts
Labels: Documentation, bug, enhancement

#25 Form errors
  .travis.yml
  package.json
  projects/crud/src/lib/components/foreign-key-field/foreign-key-field.component.ts
  projects/crud/src/lib/components/model-form/model-form.component.ts
  projects/crud/src/lib/components/select-field/select-field.component.ts
  projects/crud/src/lib/components/text-area-field/text-area-field.component.ts
  projects/crud/src/lib/containers/listing-dialog/listing-dialog.component.ts
  projects/crud/src/lib/crud.module.ts
  projects/crud/src/lib/models/metadata.ts
  projects/crud/src/lib/models/views.ts
  projects/crud/src/lib/services/form.service.ts
  projects/docs/src/app/app.component.ts
  projects/docs/src/app/app.module.ts
  projects/docs/src/app/md-viewer/md-viewer.component.ts
  projects/example-app/src/app/app.component.ts
Labels: enhancement

#29 Fix(#27): Fixed formsets data evaluation and added example
  json-mock/db.json
  projects/crud/src/lib/components/form-field/form-field.component.ts
  projects/crud/src/lib/components/formset/formset.component.html
  projects/crud/src/lib/components/formset/formset.component.ts
  projects/crud/src/lib/components/listing/listing.component.ts
  projects/crud/src/lib/components/model-form/model-form.component.html
  projects/crud/src/lib/components/model-form/model-form.component.ts
  projects/crud/src/lib/forms.ts
  projects/crud/src/lib/models/metadata.ts
  projects/crud/src/lib/models/views.ts
  projects/crud/src/lib/services/form.service.ts
  projects/crud/src/lib/services/navigator.service.ts
  projects/crud/src/lib/services/registry.service.ts
  projects/example-app/src/app/app.component.ts
  projects/example-app/src/app/app.module.ts
  projects/example-app/src/app/forms/room.edit.form.ts
  projects/example-app/src/app/forms/todo.edit.form.ts
  projects/example-app/src/app/metadata/todo.metadata.ts
  projects/example-app/src/app/models/todo.model.ts
  projects/example-app/src/app/sidenav.service.ts
Labels: bug
